### PR TITLE
Update Deps

### PR DESCRIPTION
**Pull request by SnakeDoc**
Upgraded `tom` to the latest available version. This required widening the version range in `gleam.toml` to accept the entire 1.x range. The old version range prohibited users from directly depending on `tom` 1.x versions within their project.

All dependencies have been updated in `manifest.toml` as well.

Updating `gleam_stdlib` introduced a deprecation warning on [`gleam/list.concat()`](https://hexdocs.pm/gleam_stdlib/0.41.0/gleam/list.html#concat) (https://github.com/gleam-lang/stdlib/issues/707).

This deprecation was resolved by replacing `list.concat()` with `list.flatten()`. As per the documentation, [`list.concat()`](https://github.com/gleam-lang/stdlib/blob/main/src/gleam/list.gleam#L696) and [`list.flatten()` ](https://github.com/gleam-lang/stdlib/blob/main/src/gleam/list.gleam#L720) are identical.

### CODE REVIEW

**Comment by SnakeDoc** [comment]
@maxdeviant Just following-up, hoping to help get the `tom` library updated and a fresh `startest` release out into the wild! Let me know if you need anything else on this PR. 😃

**Comment by SnakeDoc** [comment]
Note, I did not bump the `startest` version in this PR. I'm unsure what your release process is. I can add that to this PR to save you some time - no worries either way 🚀

**Comment by maxdeviant** [comment]
Thanks for the PR!

I couldn't push to this PR since the fork is on an organization, but the `tom` upgrade is in https://github.com/maxdeviant/startest/commit/d82f5cd5e01c62bd3f209208e1201590a13dafba.

I just put out v0.5.1 with the change.

**Comment by SnakeDoc** [comment]
You're the best! Thank you!

**Pull request closed without merging**
